### ISSUE TITLE
Latest version of sodium incompatible with latest version of cullleaves?

### ISSUE THREAD

**Issue by SYSK4550** [TeamMidnightDust/CullLeaves#46] opened 2023-08-20 04:36 UTC
Picked up _JAVA_OPTIONS: 
[12:34:09] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[12:34:09] [main/WARN]: Mod resolution failed
[12:34:09] [main/INFO]: Immediate reason: [HARD_DEP indium 1.0.25+mc1.20.1 {depends sodium @ [0.5.2]}, NEG_HARD_DEP sodium 0.5.2 {breaks cullleaves @ [<=3.1.0]}, ROOT_FORCELOAD_SINGLE cullleaves 3.1.0, ROOT_FORCELOAD_SINGLE indium 1.0.25+mc1.20.1]
[12:34:09] [main/INFO]: Reason: [NEG_HARD_DEP sodium 0.5.2 {breaks cullleaves @ [<=3.1.0]}]
[12:34:09] [main/INFO]: Fix: add [], remove [], replace [[sodium 0.5.2] -> add:sodium 0.5.2 ([[0.5.2,0.5.2]])]
[12:34:09] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.5.2 with version 0.5.2 that is compatible with:
		 - cullleaves 3.1.0
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.5.2 is incompatible with version 3.1.0 or earlier of mod 'Cull Leaves' (cullleaves), but a matching version is present: 3.1.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]

**Comment by m-sarabi** [comment] 2023-08-20 05:28
Duplicate of #45

**Closed** 2024-06-18 18:10 UTC
